preload = ~/Pictures/Wallpaper/wallpaper1.png
preload = ~/Pictures/Wallpaper/wallpaper.png
wallpaper = eDP-1,~/Pictures/Wallpaper/wallpaper.png
wallpaper = DP-1,~/Pictures/Wallpaper/wallpaper.png
splash = false
ipc = on