#!/bin/bash

OPTION=()

values=$(zenity \
    --title="Hyprshot GUI" \
    --text="Options" \
    --forms \
    --add-combo="Mode " \
    --combo-values="Specific area|Specific window|Whole screen" \
    --add-entry="Time to wait " \
    --add-combo="Save to" \
    --combo-values="Clipboard and file|Clipboard only|OCR (English)" \
    --add-combo="Monitor " \
    --combo-values="$(hyprctl -j monitors | jq -r 'map(.name) | join("|")')" \
    --add-combo="Directory " \
    --combo-values="~/Pictures/Screenshots|Select directory" \
) 2>/dev/null

result=$?

mode=$(echo $values | cut -d '|' -f 1)
wait=$(echo $values | cut -d '|' -f 2)
clipboard=$(echo $values | cut -d '|' -f 3)
monitor=$(echo $values | cut -d '|' -f 4)
directory=$(echo $values | cut -d '|' -f 5)

if [ "$result" -eq 1 ]; then  # select cancel
    echo "Cancelled"
    exit
fi

if [ "$directory" == "Select directory" ]; then
    FILEDIR=$(zenity --file-selection --directory --title="Choose directory to save screenshot")

    if [ "$?" -eq 1 ]; then
        FILEDIR="$HOME/Pictures/Screenshots"
    fi
else
    FILEDIR="$HOME/Pictures/Screenshots"
fi


if [ ! -z "$wait" ]; then
    sleep $wait
fi

FILENAME="Screenshot_$(date +%F_%H.%M.%S).png"

if [ "$mode" == "Specific window" ]; then  # select specify window
    MODE_OPTION="-m window"
elif [ "$mode" == "Specific area" ]; then  # select specfy area
    MODE_OPTION="-m region"
else
    MODE_OPTION="-m output"
fi

if [ ! -z "$monitor" ]; then
    MODE_OPTION+=(" -m $monitor")
fi


if [ "$clipboard" == "Clipboard only" ]; then
    hyprshot $MODE_OPTION --clipboard-only
elif [ "$clipboard" == "Clipboard and file" ]; then
    hyprshot $MODE_OPTION -o $FILEDIR -f $FILENAME
else 
    hyprshot $MODE_OPTION -o $FILEDIR -f "OCR.png"
    tesseract -l eng /home/xujus/Pictures/Screenshots/OCR.png stdout | wl-copy
fi

